package com.abctreinamentos;
// Generated 19/09/2019 11:10:06 by Hibernate Tools 4.3.1

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

    private static final long SerialVersionUID = 1L;
    private Integer id;
    private String cpf;
    private String nome;
    private String email;

    public Cliente() {
    }

    public Cliente(String cpf, String nome, String email) {
        this.cpf = cpf;
        this.nome = nome;
        this.email = email;
    }
    
    public Cliente(int id, String cpf, String nome, String email) {
        this.id = id;
        this.cpf = cpf;
        this.nome = nome;
        this.email = email;
    }
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return "Cliente {id = "+id+ ", nome=" + nome + ", cpf = " + cpf + ", email = " + email + "}";
    }

}
