package com.abctreinamentos;
// Generated 19/09/2019 11:10:06 by Hibernate Tools 4.3.1

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

    private static final long SerialVersionUID = 1L;
    private int codcurso;
    private String nome;
    private long valor;
    private String url;

    public Curso() {
    }

    public Curso(int codcurso, String nome, long valor, String url) {
        this.codcurso = codcurso;
        this.nome = nome;
        this.valor = valor;
        this.url = url;
    }

    public int getCodcurso() {
        return this.codcurso;
    }

    public void setCodcurso(int codcurso) {
        this.codcurso = codcurso;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public long getValor() {
        return this.valor;
    }

    public void setValor(long valor) {
        this.valor = valor;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        return "Curso {codigo="+codcurso+", nome=" + nome + ", valor = " + valor + ", url = " + url + "}";
    }
}
