package com.abctreinamentos;
// Generated 19/09/2019 11:10:06 by Hibernate Tools 4.3.1

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento implements java.io.Serializable {

    private PagamentoId id;
    private String datainscricao;

    public Pagamento() {
    }

    public Pagamento(PagamentoId id) {
        this.id = id;
    }

    public Pagamento(PagamentoId id, String datainscricao) {
        this.id = id;
        this.datainscricao = datainscricao;
    }

    public PagamentoId getId() {
        return this.id;
    }

    public void setId(PagamentoId id) {
        this.id = id;
    }

    public String getDatainscricao() {
        return this.datainscricao;
    }

    public void setDatainscricao(String datainscricao) {
        this.datainscricao = datainscricao;
    }

    @Override
    public String toString() {
        return "Pagamento {id=" + id.getId()+ ", codcurso=" + id.getCodcurso() + ", data inscrição = " + datainscricao + "}";
    }
}
